var adsarea = {
  'www.bing.com/search': ['.b_ad'],
  'beijing.douban.com/': ['#dale_location_home_top_right', '#dale_location_home_bottom_right'],
  'www.douban.com/*':['#dale_anonymous_homepage_top_for_crazy_ad','#dale_personal_note_top_right','#dale_personal_note_middle_right'],
  'music.douban.com/':['#dale_music_home_bottom_right', "#dale_music_home_top_right"],
  'book.douban.com/':['#dale_book_home_bottem_right', '#dale_book_home_top_right'],
  'movie.douban.com/':['#dale_movie_home_bottom_right', '#dale_movie_home_top_right','#dale_movie_subject_photos_top_right', '#dale_movie_subject_photo_middle_right'],
  'movie.douban.com/photos/*':['#dale_movie_home_bottom_right', '#dale_movie_home_top_right','#dale_movie_subject_photos_top_right', '#dale_movie_subject_photo_middle_right'],
  'www.douban.com/group/explore':['#dale_group_explore_bottom_right'],
  'www.douban.com/group/topic/*':['#dale_group_topic_new_top_right', '#dale_group_topic_new_bottom_right'],
  'www.douban.com/event/*':['#dale_event_page_top_right', '#dale_event_page_bottom_right'],
  'movie.douban.com/subject/*':['#dale_movie_subject_top_right', '#dale_movie_subject_middle_right','#dale_movie_subject_photos_top_right'],
  'book.douban.com/subject/*':['#dale_book_subject_top_right', '#dale_book_subject_middle_right'],
  'www.zhihu.com/*':['.Banner'],
  'weibo.com/*':['#v6_pl_rightmod_ads36', '.WB_right_module M_sc_right', '#v6_pl_rightmod_ads35'],
  'news.sohu.com*':['.ad300','.ad260'],
  'www.sohu.com/*':['.ad300', '.godR'],
  'news.163.com/*':['iframe','div[id^=BAIDU_SSP__wrapper_]','.gg300','.inner','.skuImg', '.mt12.mod_ad_1.mod_ad_r','.mod_ad_2','.mod_ad_3','.mod_ad_4','.mod_ad_5','.mod_ad_6','.mod_ad_7','.mod_ad_8','.mod_ad_9','.mod_ad_10','iframe', '#js-epTabDS'],
  'www.jiankang.com/*':['div[id^=BAIDU_SSP__wrapper_]'],
  'blog.163.com/*':['.m-rtopad','#r_mkaolaadv'],
  'zhidao.baidu.com/*':['#union-asplu','div[style="padding: 20px 9px 20px 10px;widget:250px;height:250px;"]'],
  'www.jb51.net/*':['#BAIDU_SSP__wrapper*'],
  'baike.baidu.com/*':['.union-content'],
  'baijia.baidu.com/*':['div[id^=BAIDU_SSP__wrapper_u]'],
  'cankaoxiaoxi.com/*':['div[id^=BAIDU_SSP__wrapper]','div[id^=tanxssp_con_mm]', 'div.mar-t-10'],
  'pan.baidu.com/*':['#web-right-view'],
  'www.bilibili.com/*':['.bilibili-player-promote-wrap'],
  'news.sina.com.cn/*':['#PublicRelation2','.side-c', '#blk_btnad_1','#blk_btnad_2'],
  'news.ifeng.com/*':['div[id^=BAIDU_SSP__wrapper_]','#iis_al_174','#iis_al_5952','div[style="clear:both;position:relative;margin:0 auto;width:300px;height:250px;"]','#padhide_1100','#padhide_1727','#padhide_527','#padhide_1954','.blockR.iphone_none.ipad_none','#iis2_rtbs_174','.adR01','#wrapper','.pic300.iphone_none.ipad_none','.bd_t5','.right_gg.mt18','.gg3.mt14'],
  'news.qq.com/*':['.article_ad.mar-b-10','#gdt_72058763092022479','#taobaoADJS','.ad-box.mar-b-30','.ad-box.mar-b-10'],
  'news.sohu.com/*':['.ad300','#beans_14174'],
  'finance.people.com.cn/*':['.banner03.clearfix','div[id^=tanxssp_con_mm]'],
  'news.xinhuanet.com/*':['.ad'],
  'military.cctv.com/*':['iframe'],
  'news.china.com/*':['div[id^=BAIDU_SSP__wrapper_]','.side_dvs.padtop10'],
  'huaban.com/*':['.pin.side.promotion', '.pro-google'],
  'sakimichan.deviantart.com/*':['.dp-ad-visible','.partial-ad'],
  'www.199it.com/*':['.textwidget'],
  'kindlefere.com/*':['.adsbygoogle'],
  'www.facebook.com/*':['.ego_section'],
  'ww.xitek.com/*':['.ad1', '.ad2'],
  'vision.xitek.com/*':['#mo544','#mo543','#mo545'],
  'dig.chouti.com/*':['#advertIframe'],
  'music.baidu.com/*':['.ad','.ad-banner'],
  'deviantart.com/':['.null'],
  'chuansong.me/*':['.section'],
  'mt.sohu.com/*':['#god_1', '#god_2','#god_3','#god_4','#god_fix_container'],
  'news.sina.com.cn/':['#blk_btnad_1','#blk_btnad_2']
};

var whitelist = {
  'baijia.baidu.com/*':[0],
  'chuansong.me/*':[0, 1, 2, 4, 6],
  'cankaoxiaoxi.com/*':[0, 1, 2, 3, 5, 6, 7, 8, 9, 10, 11, 12, 13, 15, 16, 17, 18, 23, 25, 26, 27, 28, 29, 30, 31],
  'kindlefere.com/*':[0, 1, 6, 7, 8],
  'news.sina.com.cn/*':[0, 2, 3, 6, 9, 11],
  'news.ifeng.com/*':[0, 1, 2, 6, 12, 16],
  'news.163.com/*':[0, 1, 2, 3, 4, 7, 8, 12, 13, 14, 27, 28, 29, 30, 31, 32, 312, 313],
  'military.cctv.com/*':[0, 2, 3, 7, 9],
  'news.china.com/*':[0, 1, 3, 5, 9, 7, 11, 12, 13, 14],
  'sakimichan.deviantart.com/*':[0, 1, 2],
  'www.199it.com/*':[0, 1, 3, 4, 5, 6, 7, 8, 9],
  'kindlefere.com/*':[0, 1, 2],
  'ww.xitek.com/*':[0, 1, 2],
  'music.baidu.com/*':[0, 1],
  'www.jiankang.com/*':[0, 1, 2, 5, 6, 15],
  'news.qq.com/*':[3, 5],
  'news.sina.com.cn/':[999],
  'news.ifeng.com/':[999],
  'bbs.hupu.com/*': [1]
}
